//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBotGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// コマンドやBOTからの応答メッセージデータ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("コマンドやBOTからの応答メッセージデータ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Project\\DiscordBotGUI\\DiscordBotGUI\\bin\\Debug")]
        public string CmdConfigPath {
            get {
                return ((string)(this["CmdConfigPath"]));
            }
            set {
                this["CmdConfigPath"] = value;
            }
        }
        
        /// <summary>
        /// ログファイルのフォルダパス
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ログファイルのフォルダパス")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DiscordBotGUI")]
        public string LogFilePath {
            get {
                return ((string)(this["LogFilePath"]));
            }
            set {
                this["LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormSetting {
            get {
                return ((bool)(this["FormSetting"]));
            }
            set {
                this["FormSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int MainForm_FormX {
            get {
                return ((int)(this["MainForm_FormX"]));
            }
            set {
                this["MainForm_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MainForm_FormY {
            get {
                return ((int)(this["MainForm_FormY"]));
            }
            set {
                this["MainForm_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainForm_PositionX {
            get {
                return ((int)(this["MainForm_PositionX"]));
            }
            set {
                this["MainForm_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainForm_PositionY {
            get {
                return ((int)(this["MainForm_PositionY"]));
            }
            set {
                this["MainForm_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainForm_Init {
            get {
                return ((bool)(this["MainForm_Init"]));
            }
            set {
                this["MainForm_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int Setting_FormX {
            get {
                return ((int)(this["Setting_FormX"]));
            }
            set {
                this["Setting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Setting_FormY {
            get {
                return ((int)(this["Setting_FormY"]));
            }
            set {
                this["Setting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_PositionX {
            get {
                return ((int)(this["Setting_PositionX"]));
            }
            set {
                this["Setting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_PositionY {
            get {
                return ((int)(this["Setting_PositionY"]));
            }
            set {
                this["Setting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_Init {
            get {
                return ((bool)(this["Setting_Init"]));
            }
            set {
                this["Setting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int Edit_FormX {
            get {
                return ((int)(this["Edit_FormX"]));
            }
            set {
                this["Edit_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Edit_FormY {
            get {
                return ((int)(this["Edit_FormY"]));
            }
            set {
                this["Edit_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Edit_PositionX {
            get {
                return ((int)(this["Edit_PositionX"]));
            }
            set {
                this["Edit_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Edit_PositionY {
            get {
                return ((int)(this["Edit_PositionY"]));
            }
            set {
                this["Edit_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Edit_Init {
            get {
                return ((bool)(this["Edit_Init"]));
            }
            set {
                this["Edit_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int QASetting_FormX {
            get {
                return ((int)(this["QASetting_FormX"]));
            }
            set {
                this["QASetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int QASetting_FormY {
            get {
                return ((int)(this["QASetting_FormY"]));
            }
            set {
                this["QASetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QASetting_PositionX {
            get {
                return ((int)(this["QASetting_PositionX"]));
            }
            set {
                this["QASetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QASetting_PositionY {
            get {
                return ((int)(this["QASetting_PositionY"]));
            }
            set {
                this["QASetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QASetting_Init {
            get {
                return ((bool)(this["QASetting_Init"]));
            }
            set {
                this["QASetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int DeleteSetting_FormX {
            get {
                return ((int)(this["DeleteSetting_FormX"]));
            }
            set {
                this["DeleteSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int DeleteSetting_FormY {
            get {
                return ((int)(this["DeleteSetting_FormY"]));
            }
            set {
                this["DeleteSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeleteSetting_PositionX {
            get {
                return ((int)(this["DeleteSetting_PositionX"]));
            }
            set {
                this["DeleteSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeleteSetting_PositionY {
            get {
                return ((int)(this["DeleteSetting_PositionY"]));
            }
            set {
                this["DeleteSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteSetting_Init {
            get {
                return ((bool)(this["DeleteSetting_Init"]));
            }
            set {
                this["DeleteSetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int BanSetting_FormX {
            get {
                return ((int)(this["BanSetting_FormX"]));
            }
            set {
                this["BanSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int BanSetting_FormY {
            get {
                return ((int)(this["BanSetting_FormY"]));
            }
            set {
                this["BanSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BanSetting_PositionX {
            get {
                return ((int)(this["BanSetting_PositionX"]));
            }
            set {
                this["BanSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BanSetting_PositionY {
            get {
                return ((int)(this["BanSetting_PositionY"]));
            }
            set {
                this["BanSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BanSetting_Init {
            get {
                return ((bool)(this["BanSetting_Init"]));
            }
            set {
                this["BanSetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int KickSetting_FormX {
            get {
                return ((int)(this["KickSetting_FormX"]));
            }
            set {
                this["KickSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int KickSetting_FormY {
            get {
                return ((int)(this["KickSetting_FormY"]));
            }
            set {
                this["KickSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KickSetting_PositionX {
            get {
                return ((int)(this["KickSetting_PositionX"]));
            }
            set {
                this["KickSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KickSetting_PositionY {
            get {
                return ((int)(this["KickSetting_PositionY"]));
            }
            set {
                this["KickSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KickSetting_Init {
            get {
                return ((bool)(this["KickSetting_Init"]));
            }
            set {
                this["KickSetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int RoleSetting_FormX {
            get {
                return ((int)(this["RoleSetting_FormX"]));
            }
            set {
                this["RoleSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int RoleSetting_FormY {
            get {
                return ((int)(this["RoleSetting_FormY"]));
            }
            set {
                this["RoleSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RoleSetting_PositionX {
            get {
                return ((int)(this["RoleSetting_PositionX"]));
            }
            set {
                this["RoleSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RoleSetting_PositionY {
            get {
                return ((int)(this["RoleSetting_PositionY"]));
            }
            set {
                this["RoleSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RoleSetting_Init {
            get {
                return ((bool)(this["RoleSetting_Init"]));
            }
            set {
                this["RoleSetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int WeatherInfoSetting_FormX {
            get {
                return ((int)(this["WeatherInfoSetting_FormX"]));
            }
            set {
                this["WeatherInfoSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int WeatherInfoSetting_FormY {
            get {
                return ((int)(this["WeatherInfoSetting_FormY"]));
            }
            set {
                this["WeatherInfoSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WeatherInfoSetting_PositionX {
            get {
                return ((int)(this["WeatherInfoSetting_PositionX"]));
            }
            set {
                this["WeatherInfoSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WeatherInfoSetting_PositionY {
            get {
                return ((int)(this["WeatherInfoSetting_PositionY"]));
            }
            set {
                this["WeatherInfoSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WeatherInfoSetting_Init {
            get {
                return ((bool)(this["WeatherInfoSetting_Init"]));
            }
            set {
                this["WeatherInfoSetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int JoiningLeavingSetting_FormX {
            get {
                return ((int)(this["JoiningLeavingSetting_FormX"]));
            }
            set {
                this["JoiningLeavingSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int JoiningLeavingSetting_FormY {
            get {
                return ((int)(this["JoiningLeavingSetting_FormY"]));
            }
            set {
                this["JoiningLeavingSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JoiningLeavingSetting_PositionX {
            get {
                return ((int)(this["JoiningLeavingSetting_PositionX"]));
            }
            set {
                this["JoiningLeavingSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JoiningLeavingSetting_PositionY {
            get {
                return ((int)(this["JoiningLeavingSetting_PositionY"]));
            }
            set {
                this["JoiningLeavingSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JoiningLeavingSetting_Init {
            get {
                return ((bool)(this["JoiningLeavingSetting_Init"]));
            }
            set {
                this["JoiningLeavingSetting_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int VersionInfo_FormX {
            get {
                return ((int)(this["VersionInfo_FormX"]));
            }
            set {
                this["VersionInfo_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int VersionInfo_FormY {
            get {
                return ((int)(this["VersionInfo_FormY"]));
            }
            set {
                this["VersionInfo_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VersionInfo_PositionX {
            get {
                return ((int)(this["VersionInfo_PositionX"]));
            }
            set {
                this["VersionInfo_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VersionInfo_PositionY {
            get {
                return ((int)(this["VersionInfo_PositionY"]));
            }
            set {
                this["VersionInfo_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VersionInfo_Init {
            get {
                return ((bool)(this["VersionInfo_Init"]));
            }
            set {
                this["VersionInfo_Init"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int LicenseInfoSetting_FormX {
            get {
                return ((int)(this["LicenseInfoSetting_FormX"]));
            }
            set {
                this["LicenseInfoSetting_FormX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int LicenseInfoSetting_FormY {
            get {
                return ((int)(this["LicenseInfoSetting_FormY"]));
            }
            set {
                this["LicenseInfoSetting_FormY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LicenseInfoSetting_PositionX {
            get {
                return ((int)(this["LicenseInfoSetting_PositionX"]));
            }
            set {
                this["LicenseInfoSetting_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LicenseInfoSetting_PositionY {
            get {
                return ((int)(this["LicenseInfoSetting_PositionY"]));
            }
            set {
                this["LicenseInfoSetting_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LicenseInfoSetting_Init {
            get {
                return ((bool)(this["LicenseInfoSetting_Init"]));
            }
            set {
                this["LicenseInfoSetting_Init"] = value;
            }
        }
    }
}
